import "../../globals.css";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function ProductLayout({ children }) {
  return (
    <html lang="en">
      <body >
      product page Layout
        {children}
        
        </body>
    </html>
  )
}
